---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: mysql-client
    image: mysql:5.7
    commands: 
      - sleep 60
      - mysql -h mysql-server -u drone -pdrone -e "CREATE TABLE IF NOT EXISTS drone_db.pipelines (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50) NOT NULL);"
      - mysql -h mysql-server -u drone -pdrone drone_db -e "INSERT IGNORE INTO drone_db.pipelines (id, name) VALUES (NULL, 'drone-go');"
      - mysql -h mysql-server -u drone -pdrone drone_db -e "INSERT IGNORE INTO drone_db.pipelines (id, name) VALUES (NULL, 'drone-python');"
      - mysql -h mysql-server -u drone -pdrone drone_db -e "INSERT IGNORE INTO drone_db.pipelines (id, name) VALUES (NULL, 'drone-java');"
      - mysql -h mysql-server -u drone -pdrone drone_db -e "SELECT * FROM drone_db.pipelines;"
  
services:
  - name: mysql-server
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: drone_db
      MYSQL_USER: drone
      MYSQL_PASSWORD: drone
